### ISSUE TITLE
typing error

### ISSUE THREAD

**Issue by bcube2** [mjstraughan/CubingHistory#11]
Probably due to ctrl+c & ctrl+v: https://www.cubinghistory.com/World%20Records/WorldRecordSingles2H#1393-and-1211-shotaro-makisumi and https://www.cubinghistory.com/World%20Records/WorldRecordSingles2H#1175-to-1036 are both displaying the same scramble/solution.

**Comment by mjstraughan** [comment]
Thanks. It should have the correct scramble and solution now.
