### ISSUE TITLE
3x3x3 simulator rotation on desktop

### ISSUE THREAD

**Issue by bcube2** [mjstraughan/CubingHistory#6]
Hi,

on desktop, when rotating the simulator/layer in the 3x3 Methods section, the simulator/layer stops rotating when leaving the cube area.

Working example [here](https://animcubejs.cubing.net/sources/codes/enhancement/parameters/cube3.html?): when leaving the gray area, simulator/layer is still rotating.

**Comment by mjstraughan** [comment]
I did discuss this with Michael Feather on the AnimCubeJS GitHub. Unfortunately the issue wasn't able to be fixed at the time since I got lost in the various changes that had to be made to AnimCubeJS. If you have any suggestions, let me know.

**Comment by bcube2** [comment]
Well, clearly, the issue has nothing to do with the AnimCubeJS itself. I believe it is a consequence of setting the simulator up on your page.

Maybe Eric could help to follow what Michael Feather said to fix the issue?

**Comment by bcube2** [comment]
> If you have any suggestions, let me know.

I would suggest (as a non-programmer) the following:

- use right JS files (by comparing texts from https://github.com/cubing/AnimCubeJS/tree/gh-pages/sources/codes/js-unminified and https://github.com/mjstraughan/CubingHistory/tree/main/src/components, I can see that AnimCube3.js file is more or less the same (the biggest difference being document/canvas event listeners), while both of your AnimCube4.js and AnimCube2.js files are completely different from original ones - can you tell me why your files for 2x2x2 and 4x4x4 cubes are so different?).

I think this issue can be solved by the fix proposed by Michael Fether [here](https://github.com/cubing/AnimCubeJS/issues/37#issuecomment-2050850925). For the [other issue](https://github.com/mjstraughan/CubingHistory/issues/5), copy the process from this issue and it could fix that issue by itself :-). All assuming right JS files are used.

**Comment by bcube2** [comment]
Working as expected now. Closing.
