### ISSUE TITLE
Make text comments readable

### ISSUE THREAD

**Issue by bcube2** [mjstraughan/CubingHistory#9]
On smaller screens like cell phones, long text comments like scramble sequences can't be fully read by users in your used version of AnimCubeJS simulators.

Text comments on multiple lines are supported in the latest version of AnimCubeJS simulators so consider an upgrade.

**Comment by mjstraughan** [comment]
I updated and text is wrapping as expected now. Thanks!

**Comment by bcube2** [comment]
Glad to hear that :-)
